name: CI-Rsync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-via-rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rsync Deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: '--delete --exclude=.env'
          path: .
          remote_path: /phoenix-storage/srv/introcee/testdeploy
          remote_host: svcover.nl
          remote_user: introcee
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
